name: Request a launchpad build

inputs:
  snap_name:
    description: "Name of the snap"
    required: true
  architecture:
    description: "Target build architecture, such as: amd64, arm64, armhf"
    required: true
  consumer_name:
    description: "Launchpad consumer name (consumer key)"
    required: true
  access_token:
    description: "Launchpad access token"
    required: true
  access_secret:
    description: "Launchpad access secret"
    required: true
  ubuntu_series:
    description: "Ubuntu series, such as: jammy, focal"
    required: true
    default: focal

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install launchpadlib

    - name: Request build
      shell: bash
      run: python request-build.py
      env:
        CONSUMER_NAME: ${{inputs.consumer_name}}
        ACCESS_TOKEN: ${{inputs.access_token}}
        ACCESS_SECRET: ${{inputs.access_secret}}
        SNAP_NAME: ${{inputs.snap_name}}
        ARCH: ${{inputs.architecture}}
        UBUNTU_SERIES: ${{inputs.ubuntu_series}}
