name: Request a launchpad build

inputs:
  snap_name:
    description: "Name of the snap"
    required: true
  architecture:
    description: "Target build architecture, such as: amd64, arm64, armhf"
    required: true
  consumer_name:
    description: "Launchpad consumer name (consumer key)"
    required: true
  access_token:
    description: "Launchpad access token"
    required: true
  access_secret:
    description: "Launchpad access secret"
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install launchpadlib

    - name: Request build
      shell: python
      run: |
        import os
        import sys
        import argparse
        from launchpadlib.launchpad import Launchpad
        from launchpadlib.launchpad import Credentials
        service_root= 'production'
        launchpad = Launchpad.login("${{inputs.consumer_name}}", "${{inputs.access_token}}", "${{inputs.access_secret}}",service_root, version='devel')
        ubuntu = launchpad.distributions["ubuntu"]
        release = ubuntu.getSeries(name_or_version="focal")
        owner = launchpad.people["canonical-edgex"]
        snap = launchpad.snaps.getByName(name="${{inputs.snap_name}}", owner=owner)

        arch = release.getDistroArchSeries(archtag="${{inputs.architecture}}")
        request = snap.requestBuild(archive=ubuntu.main_archive, distro_arch_series=arch, pocket='Updates', channels={"snapcraft":"latest/stable"})
        print(request)
